"""BeyondUncertainty framework implementation.

This module provides a minimal implementation of the uncertainty propagation
framework introduced in our AAAI 2027 submission.  The goal is to show
how one might integrate step‑level uncertainty estimates into an adaptive
retrieval system.  The code below is intentionally lightweight and is
meant to serve as a starting point rather than a full‑fledged production
system.

The main components are:

* A language model interface (`LLM`) that can generate intermediate
  reasoning steps along with a per‑step uncertainty score.  You can
  implement this interface for ChatGPT, Gemini, Claude, or any other
  model that exposes stepwise generation and uncertainty estimation.

* A retriever interface (`Retriever`) that retrieves supporting evidence
  when uncertainty is high.  This could be an ElasticSearch index over
  Wikipedia, a vector store, or any other search system.

* A controller that orchestrates reasoning, uncertainty estimation and
  retrieval.  It aggregates uncertainty scores and decides whether to
  continue reasoning, trigger retrieval, stop early, or abstain.

To use this framework, implement `LLM.generate_step` and
`Retriever.retrieve` for your specific model and search backend.  Then
pass instances of these classes into `BeyondUncertaintyFramework.answer`.

Example:

```
from beyond_uncertainty_framework import BeyondUncertaintyFramework, LLM, Retriever

class MyModel(LLM):
    def generate_step(self, question, context, history):
        # call your LLM here
        step = call_my_llm(question, context, history)
        uncertainty = compute_uncertainty(step)  # custom scoring
        return step, uncertainty

class MyRetriever(Retriever):
    def retrieve(self, question, history):
        return search_wikipedia(question)

framework = BeyondUncertaintyFramework(MyModel(), MyRetriever())
answer = framework.answer(question, context)
```

"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Tuple, Optional, Protocol, Any


class LLM(Protocol):
    """Interface for language models that support stepwise reasoning.

    Implementors should return a tuple of (`step_output`, `uncertainty_score`).
    The uncertainty score should be a float where higher values indicate
    greater uncertainty.  The exact scale is up to you, but values in
    `[0, 1]` are convenient for thresholding.
    """

    def generate_step(self, question: str, context: str, history: List[str]) -> Tuple[str, float]:
        raise NotImplementedError


class Retriever(Protocol):
    """Interface for external retrieval systems.

    Given a question and the current reasoning history, return a list of
    evidence strings that should be injected into the context.  The
    retrieval is triggered only when the controller decides it is needed.
    """

    def retrieve(self, question: str, history: List[str]) -> List[str]:
        raise NotImplementedError


@dataclass
class ControllerConfig:
    """Configuration parameters for the BeyondUncertainty controller."""

    max_steps: int = 5
    uncertainty_threshold: float = 0.5
    max_retrievals: int = 1


class BeyondUncertaintyFramework:
    """Core class that orchestrates reasoning, uncertainty estimation and retrieval."""

    def __init__(self, model: LLM, retriever: Retriever, config: Optional[ControllerConfig] = None) -> None:
        self.model = model
        self.retriever = retriever
        self.config = config or ControllerConfig()

    def answer(self, question: str, context: str) -> Tuple[str, float, List[str]]:
        """Generate an answer along with its uncertainty and reasoning history.

        Parameters
        ----------
        question : str
            The user question.
        context : str
            Initial context or background information (may be empty).

        Returns
        -------
        answer : str
            The final answer produced by the model.
        answer_uncertainty : float
            A numerical estimate of the uncertainty associated with the answer.
        history : List[str]
            List of intermediate reasoning steps generated by the model.
        """
        history: List[str] = []
        answer: str = ""
        answer_uncertainty: float = 1.0
        retrievals_used = 0

        for step_idx in range(self.config.max_steps):
            step, uncertainty = self.model.generate_step(question, context, history)
            history.append(step)
            answer = step  # assume last step is the answer for simplicity
            answer_uncertainty = uncertainty

            # decide whether to trigger retrieval
            if uncertainty > self.config.uncertainty_threshold and retrievals_used < self.config.max_retrievals:
                evidence_list = self.retriever.retrieve(question, history)
                if evidence_list:
                    # inject retrieved evidence into context and continue
                    context += "\n" + "\n".join(evidence_list)
                    retrievals_used += 1
                    continue

            # if uncertainty is low enough or max retrievals reached, break
            if uncertainty <= self.config.uncertainty_threshold or step_idx == self.config.max_steps - 1:
                break

        return answer, answer_uncertainty, history


__all__ = [
    "LLM",
    "Retriever",
    "ControllerConfig",
    "BeyondUncertaintyFramework",
]